# This is a basic workflow to help you get started with Actions
name: funcs
description: 'composite run action'

runs:
  using: "composite"
  steps: 
    steps:
    - name: Echo
      shell: bash
      run: |
        export AnException=0
          export AnotherException=101
          echo "1"
