# This is a basic workflow to help you get started with Actions

name: call_func

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ./.github/actions/funcs
      - name: checkout
        run: |
          export TEST_ENV='ZH'
          ls
          mkdir zh-test
          export $FIRST_NAME='HAN'
      - name: call func
        run: |
            echo "$TEST_ENV"
            export TEST2_ENV='SS'
            echo $TEST2_ENV
            ls
            cd zh-test
            echo $FIRST_NAME

